=== erichydrick/campusnavigator/sample_configuration/locationsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/locations2" xmlns:tns="http://www.example.org/locations2" elementFormDefault="qualified">


    <complexType name="location">
    	<sequence>
    		<element name="name" type="string"></element>
            <element name="address" type="tns:address" minOccurs="0"></element>
            <element name="coordinates" type="tns:coordinates"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="description" type="string" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="campus">
    	<sequence>
    		<element name="location" type="tns:location" minOccurs="1"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    </complexType>

    <element name="campus" type="tns:campus"></element>

    <complexType name="coordinates">
    	<sequence>
    		<element name="latitude" type="double"></element>
    		<element name="longitude" type="double"></element>
    	</sequence>
    </complexType>


    <complexType name="address">
    	<sequence>
    		<element name="street" type="string"></element>
    		<element name="cityStateZip" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== erichydrick/campusnavigator/sample_configuration/locations.xml
<?xml version="1.0" encoding="UTF-8"?>
<campus xmlns="http://www.example.org/locations2" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/locations2 locationsSchema.xsd ">

    <location>
        <name>Acorn Coffee Shop</name>
        <coordinates>
            <latitude>36.101211</latitude>
            <longitude>-79.506871</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Admissions Welcome Center</name>
        <coordinates>
            <latitude>36.104838</latitude>
            <longitude>-79.504189</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Alamance Building</name>
        <coordinates>
            <latitude>36.101852</latitude>
            <longitude>-79.504339</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Alumni Field House</name>
        <coordinates>
            <latitude>36.110737</latitude>
            <longitude>-79.508078</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Amphitheatre</name>
        <coordinates>
            <latitude>36.10179</latitude>
            <longitude>-79.501716</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Aramark</name>
        <address>
            <street>214 North Williamson Avenue</street>
            <cityStateZip>Elon NC 27244</cityStateZip>
        </address>
        <coordinates>
            <latitude>36.101713</latitude>
            <longitude>-79.50671</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Arts West</name>
        <coordinates>
            <latitude>36.103339</latitude>
            <longitude>-79.512627</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Belk Library</name>
        <coordinates>
            <latitude>36.104107</latitude>
            <longitude>-79.503514</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Belk Pavilion</name>
        <coordinates>
            <latitude>36.102443</latitude>
            <longitude>-79.501308</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Belk Track and White Field</name>
        <coordinates>
            <latitude>36.11016</latitude>
            <longitude>-79.506233</longitude>
        </coordinates>
        <description>Elon Phoenix track and field</description>
    </location>
    
    <location>
        <name>Business Services</name>
        <coordinates>
            <latitude>36.103063</latitude>
            <longitude>-79.510691</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Campus Technology Support</name>
        <address>
            <street>114 West Lebanon Avenue</street>
            <cityStateZip>Elon NC 27244</cityStateZip>
        </address>
        <coordinates>
            <latitude>36.10082</latitude>
            <longitude>-79.507622</longitude>
        </coordinates>
        <description>Supports Windows PCs and Macs.</description>
    </location>
  
    <location>
        <name>Carlton Building</name>
        <coordinates>
            <latitude>36.102071</latitude>
            <longitude>-79.504886</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Carolina Dorm</name>
        <coordinates>
            <latitude>36.102388</latitude>
            <longitude>-79.502757</longitude>
        </coordinates>
        <description>All-female dorm.</description>
    </location>
  
    <location>
        <name>Center for the Arts</name>
        <coordinates>
            <latitude>36.105064</latitude>
            <longitude>-79.506855</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Chandler Fountain</name>
        <coordinates>
            <latitude>36.106263</latitude>
            <longitude>-79.501534</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Chandler Hall</name>
        <coordinates>
            <latitude>36.108516</latitude>
            <longitude>-79.498036</longitude>
        </coordinates>
        <description>Moved to Danieley Center</description>
    </location>
  
    <location>
        <name>Chick-Fil-A</name>
        <coordinates>
            <latitude>36.101761</latitude>
            <longitude>-79.506689</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Coclough Hall</name>
        <coordinates>
            <latitude>36.108667</latitude>
            <longitude>-79.497352</longitude>
        </coordinates>
        <description>Moved to Danieley Center</description>
    </location>
  
    <location>
        <name>College Street Tap House</name>
        <address>
            <street>131 West College Avenue</street>
            <cityStateZip>Elon NC 27244</cityStateZip>
        </address>
        <coordinates>
            <latitude>36.10151</latitude>
            <longitude>-79.50789</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Colonnades Dining Hall</name>
        <coordinates>
            <latitude>36.105906</latitude>
            <longitude>-79.501437</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Danieley Center A</name>
        <coordinates>
            <latitude>36.105625</latitude>
            <longitude>-79.495547</longitude>
        </coordinates>
    </location>
    
    <location>
        <name>Danieley Center B</name>
        <coordinates>
            <latitude>36.106059</latitude>
            <longitude>-79.49581</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center C</name>
        <coordinates>
            <latitude>36.106447</latitude>
            <longitude>-79.495987</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center D</name>
        <coordinates>
            <latitude>36.10741</latitude>
            <longitude>-79.495987</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center E</name>
        <coordinates>
            <latitude>36.107561</latitude>
            <longitude>-79.495576</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center F</name>
        <coordinates>
            <latitude>36.107418</latitude>
            <longitude>-79.495037</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center G</name>
        <coordinates>
            <latitude>36.108335</latitude>
            <longitude>-79.496614</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center H</name>
        <coordinates>
            <latitude>36.108701</latitude>
            <longitude>-79.496298</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center I</name>
        <coordinates>
            <latitude>36.109158</latitude>
            <longitude>-79.495936</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center J</name>
        <coordinates>
            <latitude>36.108929</latitude>
            <longitude>-79.495458</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center K</name>
        <coordinates>
            <latitude>36.108597</latitude>
            <longitude>-79.494938</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center O</name>
        <coordinates>
            <latitude>36.107395</latitude>
            <longitude>-79.494584</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Center P</name>
        <coordinates>
            <latitude>36.10757</latitude>
            <longitude>-79.494045</longitude>
        </coordinates>
    </location>

    <location>
        <name>Danieley Commons</name>
        <coordinates>
            <latitude>36.107758</latitude>
            <longitude>-79.497188</longitude>
        </coordinates>
    </location>
 
    <location>
        <name>Driving Range and Putting Green</name>
        <coordinates>
            <latitude>36.096739</latitude>
            <longitude>-79.499592</longitude>
        </coordinates>
    </location>
  
    <location>
        <name>Duke Building</name>
        <coordinates>
            <latitude>36.102058</latitude>
            <longitude>-79.503722</longitude>
        </coordinates>
        <description>
            Mathematics and Computer Science department building.
        </description>
    </location>
  
    <location>
        <name>East Gym</name>
        <coordinates>
            <latitude>36.10231</latitude>
            <longitude>-79.49905</longitude>
        </coordinates>
        <description>Commuter parking available.</description>
    </location>
  
    <location>
        <name>Elon Community Church UCC</name>
        <address>
            <street>271 North Williamson Avenue</street>
            <cityStateZip>Elon NC 27244</cityStateZip>
        </address>
        <coordinates>
            <latitude>36.102407</latitude>
            <longitude>-79.507134</longitude>
        </coordinates>
    </location>

    <location>
        <name>Elon Elementary School</name>
        <address>
            <street>510 East Haggard Avenue</street>
            <cityStateZip>Elon NC 27244</cityStateZip>
        </address>
        <coordinates>
            <latitude>36.103957</latitude>
            <longitude>-79.499168</longitude>
        </coordinates>
    </location>

    <location>
        <name>Elon Town Center</name>
        <coordinates>
            <latitude>36.101499</latitude>
            <longitude>-79.506914</longitude>
        </coordinates>
        <description>Campus store location.</description>
    </location>
  
    <location>
